version: "3.7"
# 测试环境的docker配置，生产环境的利用production.yml替换了一些配置

services:
  app:
    image: node:12-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3001:3001
      - 80:80
    volumes:
      # 映射当前目录到app目录
      - "./:/app"
    environment:
      MONGO_USR: ${MONGO_USR}
      MONGO_PWD: ${MONGO_PWD}
      MONGO_HOST: mon
      MONGO_DB: ${MONGO_DB}
    working_dir: /app
  
  mon:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      # 映射本地的mongo数据库文件
      - ~/Documents/db/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
